name: Build and Test

on:
  push:
    branches:
      - develop

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Build and test project
        run: mvn clean test

      - name: Build and Install
        run: mvn clean install